### ISSUE TITLE
Really Impressive work!! Congratulations! 

### ISSUE THREAD

**Issue by Shicheng-Guo** [dirmeier/rnaiutilities#2]
Thanks team. Really Impressive work!! Congratulations! 

I am wondering if the website will be recovered or will be retired forever: http://www.rnaiatlas.ethz.ch/

**Comment by dirmeier** [comment]
Hello, the RNAiAtlas and this package are unrelated. For updates on RNAiAtlas I'd write the respective authors. Cheers, S
